export const FETCH_ADMIN = "FETCH_ADMIN";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";
export const TODAY_ORDERS_LIST = "TODAY_ORDERS_LIST";
export const TOTAL_ORDERS_LIST = "TOTAL_ORDERS_LIST";

export const SHOW_CATEGORIES = "SHOW_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CATEGORY_ADDED_SUCCESS_STATUS = "CATEGORY_ADDED_SUCCESS_STATUS";

export const SHOW_BRANDS = "SHOW_BRANDS";
export const ADD_BRANDS = "ADD_BRANDS";
export const BRAND_ADDED_SUCCESS_STATUS = "BRAND_ADDED_SUCCESS_STATUS";

export const UPDATE_AS_DELIVERED_SUCCESS = "UPDATE_AS_DELIVERED";

export const CLEAN_UP_DATA = "CLEAN_UP_DATA";
