export const FETCH_ADMIN="FETCH_ADMIN"
export const ADMIN_LOGIN_FAILURE="ADMIN_LOGIN_FAILURE"
export const TODAY_ORDERS_LIST="TODAY_ORDERS_LIST"

export const SHOW_CATEGORIES="SHOW_CATEGORIES"
export const ADD_CATEGORY="ADD_CATEGORY"
export const CATEGORY_ADDED_SUCCESS_STATUS="CATEGORY_ADDED_SUCCESS_STATUS"