export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const ADD_TO_CART_STATUS = "ADD_TO_CART_STATUS";
export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING";
export const FETCH_CART_ITEMS_OF_PERSON = "FETCH_CART_ITEMS_OF_PERSON";
export const DELETE_ITEM_FROM_CART="DELETE_ITEM_FROM_CART"
